python3 make_data.py --scanID scene0000_02 --data_dir ../ScanNet/scans --seed 55 --visualize
python3 make_data.py --scanID scene0006_00 --data_dir ../ScanNet/scans --seed 55 --visualize
python3 make_data.py --scanID scene0006_02 --data_dir ../ScanNet/scans --seed 55 --visualize
python3 make_data.py --scanID scene0009_01 --data_dir ../ScanNet/scans --seed 55 --visualize
python3 make_data.py --scanID scene0010_00 --data_dir ../ScanNet/scans --seed 55 --visualize
python3 make_data.py --scanID scene0014_00 --data_dir ../ScanNet/scans --seed 55 --visualize
python3 make_data.py --scanID scene0016_01 --data_dir ../ScanNet/scans --seed 55 --visualize
python3 make_data.py --scanID scene0016_02 --data_dir ../ScanNet/scans --seed 55 --visualize
python3 make_data.py --scanID scene0020_01 --data_dir ../ScanNet/scans --seed 55 --visualize
python3 make_data.py --scanID scene0025_02 --data_dir ../ScanNet/scans --seed 55 --visualize
python3 make_data.py --scanID scene0030_00 --data_dir ../ScanNet/scans --seed 55 --visualize
python3 make_data.py --scanID scene0034_01 --data_dir ../ScanNet/scans --seed 55 --visualize
python3 make_data.py --scanID scene0041_01 --data_dir ../ScanNet/scans --seed 55 --visualize
python3 make_data.py --scanID scene0043_01 --data_dir ../ScanNet/scans --seed 55 --visualize
python3 make_data.py --scanID scene0051_00 --data_dir ../ScanNet/scans --seed 55 --visualize
python3 make_data.py --scanID scene0051_01 --data_dir ../ScanNet/scans --seed 55 --visualize
python3 make_data.py --scanID scene0051_02 --data_dir ../ScanNet/scans --seed 55 --visualize
python3 make_data.py --scanID scene0051_03 --data_dir ../ScanNet/scans --seed 55 --visualize
python3 make_data.py --scanID scene0054_00 --data_dir ../ScanNet/scans --seed 55 --visualize
python3 make_data.py --scanID scene0060_01 --data_dir ../ScanNet/scans --seed 55 --visualize
python3 make_data.py --scanID scene0065_00 --data_dir ../ScanNet/scans --seed 55 --visualize
python3 make_data.py --scanID scene0067_02 --data_dir ../ScanNet/scans --seed 55 --visualize
python3 make_data.py --scanID scene0076_00 --data_dir ../ScanNet/scans --seed 55 --visualize
python3 make_data.py --scanID scene0084_01 --data_dir ../ScanNet/scans --seed 55 --visualize
python3 make_data.py --scanID scene0086_00 --data_dir ../ScanNet/scans --seed 55 --visualize
python3 make_data.py --scanID scene0086_01 --data_dir ../ScanNet/scans --seed 55 --visualize
python3 make_data.py --scanID scene0086_02 --data_dir ../ScanNet/scans --seed 55 --visualize
python3 make_data.py --scanID scene0088_00 --data_dir ../ScanNet/scans --seed 55 --visualize
python3 make_data.py --scanID scene0090_00 --data_dir ../ScanNet/scans --seed 55 --visualize
python3 make_data.py --scanID scene0092_03 --data_dir ../ScanNet/scans --seed 55 --visualize
python3 make_data.py --scanID scene0095_00 --data_dir ../ScanNet/scans --seed 55 --visualize
python3 make_data.py --scanID scene0099_00 --data_dir ../ScanNet/scans --seed 55 --visualize
python3 make_data.py --scanID scene0101_00 --data_dir ../ScanNet/scans --seed 55 --visualize
python3 make_data.py --scanID scene0101_02 --data_dir ../ScanNet/scans --seed 55 --visualize
python3 make_data.py --scanID scene0103_01 --data_dir ../ScanNet/scans --seed 55 --visualize
python3 make_data.py --scanID scene0111_01 --data_dir ../ScanNet/scans --seed 55 --visualize
python3 make_data.py --scanID scene0111_02 --data_dir ../ScanNet/scans --seed 55 --visualize
python3 make_data.py --scanID scene0112_00 --data_dir ../ScanNet/scans --seed 55 --visualize
python3 make_data.py --scanID scene0131_00 --data_dir ../ScanNet/scans --seed 55 --visualize
python3 make_data.py --scanID scene0131_01 --data_dir ../ScanNet/scans --seed 55 --visualize
python3 make_data.py --scanID scene0131_02 --data_dir ../ScanNet/scans --seed 55 --visualize
python3 make_data.py --scanID scene0132_00 --data_dir ../ScanNet/scans --seed 55 --visualize
python3 make_data.py --scanID scene0134_00 --data_dir ../ScanNet/scans --seed 55 --visualize
python3 make_data.py --scanID scene0134_01 --data_dir ../ScanNet/scans --seed 55 --visualize
python3 make_data.py --scanID scene0134_02 --data_dir ../ScanNet/scans --seed 55 --visualize
python3 make_data.py --scanID scene0136_02 --data_dir ../ScanNet/scans --seed 55 --visualize
python3 make_data.py --scanID scene0141_00 --data_dir ../ScanNet/scans --seed 55 --visualize
python3 make_data.py --scanID scene0142_01 --data_dir ../ScanNet/scans --seed 55 --visualize
python3 make_data.py --scanID scene0143_01 --data_dir ../ScanNet/scans --seed 55 --visualize
python3 make_data.py --scanID scene0143_02 --data_dir ../ScanNet/scans --seed 55 --visualize
python3 make_data.py --scanID scene0147_00 --data_dir ../ScanNet/scans --seed 55 --visualize
python3 make_data.py --scanID scene0147_01 --data_dir ../ScanNet/scans --seed 55 --visualize
python3 make_data.py --scanID scene0161_01 --data_dir ../ScanNet/scans --seed 55 --visualize
python3 make_data.py --scanID scene0164_00 --data_dir ../ScanNet/scans --seed 55 --visualize
python3 make_data.py --scanID scene0166_00 --data_dir ../ScanNet/scans --seed 55 --visualize
python3 make_data.py --scanID scene0170_02 --data_dir ../ScanNet/scans --seed 55 --visualize
python3 make_data.py --scanID scene0172_01 --data_dir ../ScanNet/scans --seed 55 --visualize
python3 make_data.py --scanID scene0174_00 --data_dir ../ScanNet/scans --seed 55 --visualize
python3 make_data.py --scanID scene0186_00 --data_dir ../ScanNet/scans --seed 55 --visualize
python3 make_data.py --scanID scene0193_00 --data_dir ../ScanNet/scans --seed 55 --visualize
python3 make_data.py --scanID scene0193_01 --data_dir ../ScanNet/scans --seed 55 --visualize
